# Generated by Django 5.2.5 on 2025-09-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="upcoming_event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("event_date", models.DateField()),
                ("event_time", models.TimeField()),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
    ]
