# Generated by Django 5.2.5 on 2025-09-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_upcoming_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="upcoming_event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
