# Generated by Django 5.2.5 on 2025-09-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_upcoming_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="event_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
