# Generated by Django 5.2.5 on 2025-09-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_eventregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="event_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
