# Generated by Django 5.2.5 on 2025-09-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_alter_signup_event_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventregistration",
            old_name="event",
            new_name="event_name",
        ),
    ]
